title: Custom Jekyll config
description: Github Pages default theme with pagination

repository: DirtyF/gh-pages-test

# Change defaults
source: src
collection_dir: content
layouts_dir:  src/theme/_layouts
includes_dir: src/theme/_includes

# Pagination
paginate: 1
paginate_path: "/page/:num/"
